### ISSUE TITLE
Apache version

### ISSUE THREAD

**Issue by svbeek** [aquenos/apache2-mod-log-ipmask#2]
Hi Sebastian, 

Nice module, thanks! I'm trying to build the module on a redhat/centos system against Apache 2.4.6 (yes ancient, i know.. but this is what comes with centos ootb). Made some changes in the Makefile to point it to the source code, but it won't build. Against what version of Apache did you develop the module? Probably a more recent one? Then I'll try that also.

Thanks
Sander

**Comment by smarsching** [comment]
I built it on Ubuntu 16.04 LTS, which is using Apache 2.4.18.

**Comment by smarsching** [comment]
On another note: I can imagine two reasons why the module might not built:

1. The Apache developer files might be in a different directory on CentOS, so the paths in `Makefile` might have to be adjusted. Of course, the developer files are usually in a separate package and have to be installed explicitly (I have no idea what the package is called on CentOS, on Ubuntu it is `apache2-dev`).
2. The C++ compiler might be too old. You will need a C++ compiler that fully supports C++ 11. While GCC 4.8.1 claims to be supporting C++ 11, it actually still has a few bugs, so effectively you will at least need GCC 4.9.

There is a PR (#1) that addresses this issue, but I intentionally did not merge this PR because I want to avoid workarounds for old compilers in order to keep the code as clean as possible.

**Comment by svbeek** [comment]
Had to use the patch for gcc 4.8.x indeed, but now it works like a charm. Thanks!
